name: Affinity Test 1
description: |
  This template sets up a service that has a label.  Then creates another service that relies on that label.  Both should end up on the same host.
version: 1.0.0
category: Test
maintainer: Tani Fiduccia
license: 9087 license
projectURL: http://www.google.com

